acme_covoiturage:
    resource: "@AcmeCovoiturageBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
 
annonceUser:
    pattern : /annonceUser
    defaults: { _controller: AcmeCovoiturageBundle:Annonce:annonceUser}
    
reservationAnnonce:
    pattern : /reservationAnnonce/{id}
    defaults: { _controller: AcmeCovoiturageBundle:Reservation:reservationAnnonce}    


acceptReservation:
    pattern : /acceptReservation/{id_ann}/{id}
    defaults: { _controller: AcmeCovoiturageBundle:Reservation:acceptReservation}    

refuseReservation:
    pattern : /refuseReservation/{id_ann}/{id}
    defaults: { _controller: AcmeCovoiturageBundle:Reservation:refuseReservation}
    
map:
    pattern : /map/{from}/{to}
    defaults: { _controller: AcmeCovoiturageBundle:Map:index}
 
annonce_search:
    pattern : /search
    defaults: { _controller: AcmeCovoiturageBundle:Annonce:searchAnnonce}

index:
    pattern : /index
    defaults: { _controller: AcmeCovoiturageBundle:Index:index}
    


avis_user:
    pattern : /avis_user/{id_ann}/{note}
    defaults: { _controller: AcmeCovoiturageBundle:Avis:avis_user}
