security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
           id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
        main:
           pattern: ^/
           form_login:
               check_path: fos_user_security_check
               login_path: fos_user_security_login
               provider: fos_userbundle
               default_target_path: /
               always_use_default_target_path: true
               failure_path: fos_user_security_login
               
           logout:
               path:    fos_user_security_logout
               target: /login
             
           
           
           anonymous:    true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/produit, role: ROLE_USER }